### ISSUE TITLE
Question on how to use/Potential Bug

### ISSUE THREAD

**Issue by grosset1** [bumbummen99/southparkdownloader#17]
Hi, just downloaded everything as described but i seem to be getting an error. I am on Win 10 and tried both the UI and Cmd line version but neither seem to work. Is it just me being incompetent?

Unhandled exception. System.ArgumentOutOfRangeException: startIndex cannot be larger than length of string. (Parameter 'startIndex')
   at System.String.Substring(Int32 startIndex, Int32 length)
   at Figgle.FiggleFont.Render(String message, Nullable`1 smushOverride)
   at SouthParkDLCommandLine.Core.Logic..ctor(String name) in D:\a\southparkdownloader\southparkdownloader\SouthParkDLCommandLine\Core\Logic.cs:line 31
   at SouthParkDLCommandLine.Logic.ApplicationLogic..ctor() in D:\a\southparkdownloader\southparkdownloader\SouthParkDLCommandLine\Logic\ApplicationLogic.cs:line 43
   at SouthParkDLCommandLine.Logic.ApplicationLogic.<>c.<.cctor>b__19_0() in D:\a\southparkdownloader\southparkdownloader\SouthParkDLCommandLine\Logic\ApplicationLogic.cs:line 31
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.get_Value()
   at SouthParkDLCommandLine.Logic.ApplicationLogic.get_Instance() in D:\a\southparkdownloader\southparkdownloader\SouthParkDLCommandLine\Logic\ApplicationLogic.cs:line 37
   at SouthParkDLCommandLine.Program.Main(String[] args) in D:\a\southparkdownloader\southparkdownloader\SouthParkDLCommandLine\Program.cs:line 10

Hope someone can help here :D

**Comment by bumbummen99** [comment]
Yeah that does look like like Figgle.FiggleFont.Render() does not get the correct parameter during construction of the Logic object. I'll look into that

https://github.com/bumbummen99/southparkdownloader/blob/master/SouthParkDLCommandLine/Core/Logic.cs#L31

**Comment by XylotoGhost** [comment]
Any update on this? Happening to me on W11 as well.

Unhandled exception. System.ArgumentOutOfRangeException: startIndex cannot be larger than length of string. (Parameter 'startIndex')
   at System.String.Substring(Int32 startIndex, Int32 length)
   at Figgle.FiggleFont.Render(String message, Nullable`1 smushOverride)
   at SouthParkDLCommandLine.Core.Logic..ctor(String name) in D:\a\southparkdownloader\southparkdownloader\SouthParkDLCommandLine\Core\Logic.cs:line 31
   at SouthParkDLCommandLine.Logic.ApplicationLogic..ctor() in D:\a\southparkdownloader\southparkdownloader\SouthParkDLCommandLine\Logic\ApplicationLogic.cs:line 43
   at SouthParkDLCommandLine.Logic.ApplicationLogic.<>c.<.cctor>b__19_0() in D:\a\southparkdownloader\southparkdownloader\SouthParkDLCommandLine\Logic\ApplicationLogic.cs:line 31
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.get_Value()
   at SouthParkDLCommandLine.Logic.ApplicationLogic.get_Instance() in D:\a\southparkdownloader\southparkdownloader\SouthParkDLCommandLine\Logic\ApplicationLogic.cs:line 37
   at SouthParkDLCommandLine.Program.Main(String[] args) in D:\a\southparkdownloader\southparkdownloader\SouthParkDLCommandLine\Program.cs:line 10

**Comment by bumbummen99** [comment]
Please try with 1.7.3

**Comment by grosset1** [comment]
Thanks for the fix. But now when i download it says
[S1E1] Starting download 1 Cartman und die Analsonde
[S1E1] YoutubeDL failed.
[S1E1] No video files to merge!
It's like that for every episode. Do you know what I can do to fix this?

**Comment by JoKerIsCraZy** [comment]
> Thanks for the fix. But now when i download it says [S1E1] Starting download 1 Cartman und die Analsonde [S1E1] YoutubeDL failed. [S1E1] No video files to merge! It's like that for every episode. Do you know what I can do to fix this?

Have the same issue

**Comment by bumbummen99** [comment]
## Repository Deprecated Notice

This repository is no longer maintained. All issues, including this one, will be closed.

Please visit [the repository](https://github.com/bumbummen99/southpark-downloader) to access the new version of SouthPark Downloader.

For an in-depth explanation on why this repository has been deprecated, please refer to the [Readme.md](https://github.com/bumbummen99/southparkdownloader#important-notice).
