### ISSUE TITLE
How to start southparkdownloader on Linux (Manjaro)?

### ISSUE THREAD

**Issue by Doomnometron** [bumbummen99/southparkdownloader#18]
Hi there,

I've downloaded the latest release (SouthParkDLCommandLine-1.7.2-linux-x64.tar.gz) but can't start the command line tool.

>[doom@manjaro SouthParkDLCommandLine-1.7.2-linux-x64]$ ./SouthParkDLCommandLine
Unhandled exception. System.ArgumentOutOfRangeException: startIndex cannot be larger than length of string. (Parameter 'startIndex')
   at System.String.Substring(Int32 startIndex, Int32 length)
   at Figgle.FiggleFont.Render(String message, Nullable'1 smushOverride)
   at SouthParkDLCommandLine.Core.Logic..ctor(String name) in /home/runner/work/southparkdownloader/southparkdownloader/SouthParkDLCommandLine/Core/Logic.cs:line 31
   at SouthParkDLCommandLine.Logic.ApplicationLogic..ctor() in /home/runner/work/southparkdownloader/southparkdownloader/SouthParkDLCommandLine/Logic/ApplicationLogic.cs:line 43
   at SouthParkDLCommandLine.Logic.ApplicationLogic.<>c.<.cctor>b__19_0() in /home/runner/work/southparkdownloader/southparkdownloader/SouthParkDLCommandLine/Logic/ApplicationLogic.cs:line 31
   at System.Lazy'1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy'1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy'1.CreateValue()
   at System.Lazy'1.get_Value()
   at SouthParkDLCommandLine.Logic.ApplicationLogic.get_Instance() in /home/runner/work/southparkdownloader/southparkdownloader/SouthParkDLCommandLine/Logic/ApplicationLogic.cs:line 37
   at SouthParkDLCommandLine.Program.Main(String[] args) in /home/runner/work/southparkdownloader/southparkdownloader/SouthParkDLCommandLine/Program.cs:line 10

fyi: I've replaced the ` into ' because of formatting.

The mentioned command 

> ./SouthParkDownloaderNetCore

doesn't work due to the file does not exist.

**Comment by bumbummen99** [comment]
Can you try with 1.7.3? Yeah you are not supposed to start the core, just CLI or GUI

**Comment by Doomnometron** [comment]
1.7.3 is working, thanks! But now I'm struggling with ytdlc.

> [doom@manjaro SouthParkDLCommandLine-1.7.3-linux-x64]$ ./SouthParkDLCommandLine --ytdlc
SouthParkDL v1.7.3.0
SouthParkDL is ready!
Loaded episode index.
$download
[S1E4] Starting download 4 Ein Heim für Tiertunten
[S1E2] Starting download 2 Knall endlich den Hasen ab!
[S1E3] Starting download 3 Wie werde ich ein Kampfkoloss?
[S1E1] Starting download 1 Cartman und die Analsonde
/bin/bash: Zeile 1: youtube-dl: Kommando nicht gefunden.
/bin/bash: Zeile 1: youtube-dl: Kommando nicht gefunden.
/bin/bash: Zeile 1: youtube-dl: Kommando nicht gefunden.
/bin/bash: Zeile 1: youtube-dl: Kommando nicht gefunden.

How do I add the parameter correctly?

**Comment by bumbummen99** [comment]
It looks like you have not installed youtube-dl, on linux you have to do that manually with your distros package manager

**Comment by Doomnometron** [comment]
I'm fairly new in Linux, but for my understandig all needed packages are installed.

> [doom@manjaro ~]$ sudo pacman -Ss youtube-dl
community/youtube-dl 2021.12.17-1 [Installiert]
    A command-line program to download videos from YouTube.com and a few more sites
community/yt-dlp 2022.02.04-2 [Installiert]
    A youtube-dl fork with additional features and fixes

Even youtube-dl is installed and can be started.

> [doom@manjaro ~]$ youtube-dl
Usage: youtube-dl [OPTIONS] URL [URL...]
youtube-dl: error: You must provide at least one URL.
Type youtube-dl --help to see a list of all options.

But SouthParkDLCommandLine does not seem to recognize it.

**Comment by bumbummen99** [comment]
## Repository Deprecated Notice

This repository is no longer maintained. All issues, including this one, will be closed.

Please visit [the repository](https://github.com/bumbummen99/southpark-downloader) to access the new version of SouthPark Downloader.

For an in-depth explanation on why this repository has been deprecated, please refer to the [Readme.md](https://github.com/bumbummen99/southparkdownloader#important-notice).
